// Esquema inicial de MySQL, generado por Prisma a partir de prisma/schema.prisma:
//
//   npx prisma migrate diff --from-empty \\
//     --to-schema-datamodel prisma/schema.prisma --script
//
// Se genera sin conectar a ninguna base de datos, y se guarda aquí como código
// en lugar de como .sql porque lo lee la aplicación al arrancar: un fichero
// suelto dependería de que el despliegue lo copiara, un módulo no.
//
// Hay que regenerarlo cuando cambie el esquema. NO editar a mano.

export const SENTENCIAS_ESQUEMA_INICIAL: string[] = [
  "CREATE TABLE `Organization` (\n    `id` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Business` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `type` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `legalName` VARCHAR(191) NULL,\n    `taxId` VARCHAR(191) NULL,\n    `contactEmail` VARCHAR(191) NULL,\n    `contactPhone` VARCHAR(191) NULL,\n    `address` TEXT NULL,\n    `taxRate` DECIMAL(65, 30) NOT NULL DEFAULT 7,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    UNIQUE INDEX `Business_organizationId_type_key`(`organizationId`, `type`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Owner` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `email` VARCHAR(191) NULL,\n    `phone` VARCHAR(191) NULL,\n    `notes` TEXT NULL,\n    `taxId` VARCHAR(191) NULL,\n    `address` TEXT NULL,\n    `monthlyFee` DECIMAL(65, 30) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `Owner_organizationId_idx`(`organizationId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Property` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `ownerId` VARCHAR(191) NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `locality` VARCHAR(191) NOT NULL,\n    `address` VARCHAR(191) NULL,\n    `capacity` INTEGER NOT NULL DEFAULT 2,\n    `bedrooms` INTEGER NOT NULL DEFAULT 1,\n    `bathrooms` INTEGER NOT NULL DEFAULT 1,\n    `active` BOOLEAN NOT NULL DEFAULT true,\n    `cleaningPrice` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `managementPct` DECIMAL(65, 30) NULL,\n    `groupId` VARCHAR(191) NULL,\n    `manualStatus` VARCHAR(191) NULL,\n    `lodgifyPropertyId` VARCHAR(191) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Property_lodgifyPropertyId_key`(`lodgifyPropertyId`),\n    INDEX `Property_organizationId_idx`(`organizationId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Employee` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `role` VARCHAR(191) NOT NULL DEFAULT 'CLEANING',\n    `phone` VARCHAR(191) NULL,\n    `active` BOOLEAN NOT NULL DEFAULT true,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `Employee_organizationId_idx`(`organizationId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Booking` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `propertyId` VARCHAR(191) NOT NULL,\n    `lodgifyBookingId` VARCHAR(191) NULL,\n    `guestName` VARCHAR(191) NOT NULL,\n    `guestEmail` VARCHAR(191) NULL,\n    `guestPhone` VARCHAR(191) NULL,\n    `adults` INTEGER NOT NULL DEFAULT 1,\n    `children` INTEGER NOT NULL DEFAULT 0,\n    `checkIn` DATETIME(3) NOT NULL,\n    `checkOut` DATETIME(3) NOT NULL,\n    `channel` VARCHAR(191) NOT NULL DEFAULT 'DIRECTO',\n    `status` VARCHAR(191) NOT NULL DEFAULT 'CONFIRMED',\n    `totalPrice` DECIMAL(65, 30) NOT NULL,\n    `platformCommissionPct` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `platformCommissionAmt` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `bankCommissionPct` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `bankCommissionAmt` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `netAmount` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `manuallyAdjusted` BOOLEAN NOT NULL DEFAULT false,\n    `notes` TEXT NULL,\n    `source` VARCHAR(191) NOT NULL DEFAULT 'MANUAL',\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Booking_lodgifyBookingId_key`(`lodgifyBookingId`),\n    INDEX `Booking_organizationId_idx`(`organizationId`),\n    INDEX `Booking_propertyId_idx`(`propertyId`),\n    INDEX `Booking_checkIn_idx`(`checkIn`),\n    INDEX `Booking_checkOut_idx`(`checkOut`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `CleaningTask` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `propertyId` VARCHAR(191) NOT NULL,\n    `bookingId` VARCHAR(191) NULL,\n    `type` VARCHAR(191) NOT NULL DEFAULT 'CLEANING',\n    `date` DATETIME(3) NOT NULL,\n    `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',\n    `employeeId` VARCHAR(191) NULL,\n    `billable` BOOLEAN NOT NULL DEFAULT true,\n    `price` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `invoiceId` VARCHAR(191) NULL,\n    `notes` TEXT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    INDEX `CleaningTask_organizationId_idx`(`organizationId`),\n    INDEX `CleaningTask_propertyId_idx`(`propertyId`),\n    INDEX `CleaningTask_date_idx`(`date`),\n    INDEX `CleaningTask_status_idx`(`status`),\n    INDEX `CleaningTask_invoiceId_idx`(`invoiceId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Partner` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `email` VARCHAR(191) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `Partner_organizationId_idx`(`organizationId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `PartnerSplitConfig` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `partnerAId` VARCHAR(191) NOT NULL,\n    `partnerBId` VARCHAR(191) NOT NULL,\n    `partnerAPercent` DECIMAL(65, 30) NOT NULL DEFAULT 50,\n    `partnerBPercent` DECIMAL(65, 30) NOT NULL DEFAULT 50,\n    `effectiveFrom` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `PartnerSplitConfig_organizationId_idx`(`organizationId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Invoice` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `invoiceNumber` VARCHAR(191) NOT NULL,\n    `billedToName` VARCHAR(191) NOT NULL,\n    `billedToTaxId` VARCHAR(191) NULL,\n    `billedToAddress` TEXT NULL,\n    `periodStart` DATETIME(3) NOT NULL,\n    `periodEnd` DATETIME(3) NOT NULL,\n    `issueDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `status` VARCHAR(191) NOT NULL DEFAULT 'DRAFT',\n    `subtotal` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `taxRate` DECIMAL(65, 30) NOT NULL DEFAULT 7,\n    `taxAmount` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `total` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `partnerAId` VARCHAR(191) NULL,\n    `partnerBId` VARCHAR(191) NULL,\n    `partnerAPercent` DECIMAL(65, 30) NOT NULL DEFAULT 50,\n    `partnerBPercent` DECIMAL(65, 30) NOT NULL DEFAULT 50,\n    `partnerAAmount` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `partnerBAmount` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `notes` TEXT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Invoice_invoiceNumber_key`(`invoiceNumber`),\n    INDEX `Invoice_organizationId_idx`(`organizationId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `InvoiceLine` (\n    `id` VARCHAR(191) NOT NULL,\n    `invoiceId` VARCHAR(191) NOT NULL,\n    `cleaningTaskId` VARCHAR(191) NULL,\n    `description` VARCHAR(191) NOT NULL,\n    `propertyName` VARCHAR(191) NOT NULL,\n    `date` DATETIME(3) NOT NULL,\n    `amount` DECIMAL(65, 30) NOT NULL,\n\n    INDEX `InvoiceLine_invoiceId_idx`(`invoiceId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `ChannelCommission` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `channel` VARCHAR(191) NOT NULL,\n    `propertyId` VARCHAR(191) NULL,\n    `platformPct` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `bankPct` DECIMAL(65, 30) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `ChannelCommission_organizationId_idx`(`organizationId`),\n    INDEX `ChannelCommission_propertyId_idx`(`propertyId`),\n    UNIQUE INDEX `ChannelCommission_organizationId_channel_propertyId_key`(`organizationId`, `channel`, `propertyId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `PropertyGroup` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `ownerId` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `managementPct` DECIMAL(65, 30) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `PropertyGroup_organizationId_idx`(`organizationId`),\n    INDEX `PropertyGroup_ownerId_idx`(`ownerId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `Expense` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `propertyId` VARCHAR(191) NULL,\n    `ownerId` VARCHAR(191) NULL,\n    `groupId` VARCHAR(191) NULL,\n    `type` VARCHAR(191) NOT NULL DEFAULT 'gasto',\n    `reparto` VARCHAR(191) NOT NULL DEFAULT 'directo',\n    `origen` VARCHAR(191) NULL,\n    `origenHash` VARCHAR(191) NULL,\n    `revisar` TEXT NULL,\n    `date` DATETIME(3) NULL,\n    `concept` VARCHAR(191) NOT NULL,\n    `supplier` VARCHAR(191) NULL,\n    `amount` DECIMAL(65, 30) NOT NULL DEFAULT 0,\n    `notes` TEXT NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    `updatedAt` DATETIME(3) NOT NULL,\n\n    UNIQUE INDEX `Expense_origenHash_key`(`origenHash`),\n    INDEX `Expense_organizationId_idx`(`organizationId`),\n    INDEX `Expense_propertyId_idx`(`propertyId`),\n    INDEX `Expense_groupId_idx`(`groupId`),\n    INDEX `Expense_date_idx`(`date`),\n    INDEX `Expense_type_idx`(`type`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `IntegrationSettings` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `provider` VARCHAR(191) NOT NULL DEFAULT 'LODGIFY',\n    `apiKeyMasked` VARCHAR(191) NULL,\n    `apiKeyCifrada` TEXT NULL,\n    `defaultPlatformPct` DECIMAL(65, 30) NOT NULL DEFAULT 15,\n    `defaultBankPct` DECIMAL(65, 30) NOT NULL DEFAULT 2.5,\n    `syncEnabled` BOOLEAN NOT NULL DEFAULT true,\n    `lastSyncAt` DATETIME(3) NULL,\n    `lastSyncSummary` TEXT NULL,\n\n    UNIQUE INDEX `IntegrationSettings_organizationId_provider_key`(`organizationId`, `provider`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `User` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `name` VARCHAR(191) NOT NULL,\n    `email` VARCHAR(191) NOT NULL,\n    `passwordHash` VARCHAR(191) NOT NULL,\n    `role` VARCHAR(191) NOT NULL DEFAULT 'STAFF',\n    `active` BOOLEAN NOT NULL DEFAULT true,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    UNIQUE INDEX `User_email_key`(`email`),\n    INDEX `User_organizationId_idx`(`organizationId`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "CREATE TABLE `DocumentoOcr` (\n    `id` VARCHAR(191) NOT NULL,\n    `organizationId` VARCHAR(191) NOT NULL,\n    `subidoPorId` VARCHAR(191) NULL,\n    `estado` VARCHAR(191) NOT NULL DEFAULT 'pendiente',\n    `archivoNombre` VARCHAR(191) NOT NULL,\n    `archivoMime` VARCHAR(191) NOT NULL,\n    `archivoBytes` INTEGER NOT NULL,\n    `archivoHash` VARCHAR(191) NOT NULL,\n    `contenido` LONGBLOB NOT NULL,\n    `datosIa` TEXT NULL,\n    `confianzaIa` VARCHAR(191) NULL,\n    `fiabilidad` DECIMAL(65, 30) NULL,\n    `motivos` TEXT NULL,\n    `avisos` TEXT NULL,\n    `datosRevisados` TEXT NULL,\n    `revisadoPorId` VARCHAR(191) NULL,\n    `revisadoEn` DATETIME(3) NULL,\n    `modelo` VARCHAR(191) NULL,\n    `promptVersion` VARCHAR(191) NULL,\n    `tokensEntrada` INTEGER NULL,\n    `tokensSalida` INTEGER NULL,\n    `tokensCache` INTEGER NULL,\n    `errorLectura` TEXT NULL,\n    `expenseId` VARCHAR(191) NULL,\n    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n\n    INDEX `DocumentoOcr_organizationId_idx`(`organizationId`),\n    INDEX `DocumentoOcr_estado_idx`(`estado`),\n    INDEX `DocumentoOcr_archivoHash_idx`(`archivoHash`),\n    PRIMARY KEY (`id`)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "ALTER TABLE `Business` ADD CONSTRAINT `Business_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Owner` ADD CONSTRAINT `Owner_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Property` ADD CONSTRAINT `Property_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Property` ADD CONSTRAINT `Property_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `Owner`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `Property` ADD CONSTRAINT `Property_groupId_fkey` FOREIGN KEY (`groupId`) REFERENCES `PropertyGroup`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `Employee` ADD CONSTRAINT `Employee_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Booking` ADD CONSTRAINT `Booking_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Booking` ADD CONSTRAINT `Booking_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `CleaningTask` ADD CONSTRAINT `CleaningTask_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `CleaningTask` ADD CONSTRAINT `CleaningTask_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `CleaningTask` ADD CONSTRAINT `CleaningTask_bookingId_fkey` FOREIGN KEY (`bookingId`) REFERENCES `Booking`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `CleaningTask` ADD CONSTRAINT `CleaningTask_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `Employee`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `CleaningTask` ADD CONSTRAINT `CleaningTask_invoiceId_fkey` FOREIGN KEY (`invoiceId`) REFERENCES `Invoice`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `Partner` ADD CONSTRAINT `Partner_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `PartnerSplitConfig` ADD CONSTRAINT `PartnerSplitConfig_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Invoice` ADD CONSTRAINT `Invoice_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `InvoiceLine` ADD CONSTRAINT `InvoiceLine_invoiceId_fkey` FOREIGN KEY (`invoiceId`) REFERENCES `Invoice`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `ChannelCommission` ADD CONSTRAINT `ChannelCommission_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `ChannelCommission` ADD CONSTRAINT `ChannelCommission_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `PropertyGroup` ADD CONSTRAINT `PropertyGroup_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `PropertyGroup` ADD CONSTRAINT `PropertyGroup_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `Owner`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Expense` ADD CONSTRAINT `Expense_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `Expense` ADD CONSTRAINT `Expense_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `Expense` ADD CONSTRAINT `Expense_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `Owner`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `Expense` ADD CONSTRAINT `Expense_groupId_fkey` FOREIGN KEY (`groupId`) REFERENCES `PropertyGroup`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
  "ALTER TABLE `IntegrationSettings` ADD CONSTRAINT `IntegrationSettings_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `User` ADD CONSTRAINT `User_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `DocumentoOcr` ADD CONSTRAINT `DocumentoOcr_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE",
  "ALTER TABLE `DocumentoOcr` ADD CONSTRAINT `DocumentoOcr_subidoPorId_fkey` FOREIGN KEY (`subidoPorId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE",
];
